### ISSUE TITLE
最大最小距离-代码异常。

### ISSUE THREAD

**Issue by alexgaoyh** [W-angler/cluster#1]
Cluster.java

	private static Point biggestLeastDistance(List<Point> points,List<Point> centers){
		return points.parallelStream()
			.reduce((p1,p2)->minDistance(p1,centers)>minDistance(p1,centers)?p1:p2)
			.get();
	}

这里应该是： 
   .reduce((p1,p2)->minDistance(p1,centers)>minDistance(p2,centers)?p1:p2)

**Comment by W-angler** [comment]
噢是的这里写错了，感谢指正！没想到多年前的代码还有人看😂
